CREATE TABLE [dbo].[PAYMENT_REGISTRATION] (
    [PAYMNET_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [COSTUMER_ID]    INT            NOT NULL,
    [ROOM_ID]        INT            NOT NULL,
    [ENTRY_DATE]     DATE           NULL,
    [RELEASE_DATE]   DATE           NULL,
    [PAYMENT_AMOUNT] NUMERIC (5, 2) NULL,
    [EXPLANATION]    VARCHAR (50)   NULL,
    CONSTRAINT [PK_PAYMENT_REGISTRATION] PRIMARY KEY CLUSTERED ([PAYMNET_ID] ASC)
);

