CREATE TABLE [dbo].[ROOM_INFORMATION] (
    [ROOM_ID]   INT            IDENTITY (1, 1) NOT NULL,
    [ROOM_FLAG] TINYINT        NULL,
    [FLOOR]     TINYINT        NULL,
    [FULLNESS]  TINYINT        NULL,
    [PRICE]     NUMERIC (5, 2) NULL,
    [ROOM_NO]   INT            NULL,
    CONSTRAINT [PK_ROOM_INFORMATION] PRIMARY KEY CLUSTERED ([ROOM_ID] ASC)
);

