CREATE TABLE [dbo].[CUSTOMER_REGISTRATIONS] (
    [CUSTOMER_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [CUSTOMER_NAME]    VARCHAR (50)  NULL,
    [CUSTOMER_SURNAME] VARCHAR (50)  NULL,
    [PHONE_NUMBER]     VARCHAR (10)  NULL,
    [EMAIL]            VARCHAR (50)  NULL,
    [EXPLANATION]      VARCHAR (100) NULL,
    [COUNTRT]          VARCHAR (20)  NULL,
    [CITY]             VARCHAR (20)  NULL,
    [COUNTY]           VARCHAR (20)  NULL,
    [INVOICE_ADDRESS]  VARCHAR (50)  NULL,
    [HES_CODE]         VARCHAR (10)  NULL,
    CONSTRAINT [PK_CUSTOMER_REGISTRATIONS] PRIMARY KEY CLUSTERED ([CUSTOMER_ID] ASC)
);

